# version: '3.4'

# services:
#   webapi:
#     image: ${DOCKER_REGISTRY-}webapi
#     build:
#       context: .
#       dockerfile: WebAPI/Dockerfile



# version: '3.4'

# services:
#   s_test_database:
#     container_name: c_test_database
#     image: mcr.microsoft.com/mssql/server:2022-latest
#     ports:
#        - 1433:1433
#     environment: 
#        - MSSQL_SA_PASSWORD=myStong_Password123#!
#        - ACCEPT_EULA=Y
#     volumes: 
#        - volume_test_database:/var/opt/mssql
#   webapi:
#     container_name: c_test_webapi
#     image: ${DOCKER_REGISTRY-}webapi
#     build:
#         context: .
#         dockerfile: WebAPI/Dockerfile
#     ports:
#       - 7000:80
#     depends_on:
#       - s_test_database
# volumes:
#   volume_test_database:


version: '3.4'

services:
  s_test_database:
    container_name: c_test_database
    image: "mysql" 
    ports:
      - 6060:3306
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_PASSWORD: myStong_Password123#!
      MYSQL_DB: database_mysql  
    restart: always
    volumes:
      - volume_test2_database:/etc/mysql/conf.d
  webapi:
    container_name: c_test_webapi
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    ports:
      - 7070:80
    depends_on:
      - s_test_database
volumes:
  volume_test2_database: 